apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: cm9vdA==
  password: YWRtaW4xMjM=

##Use Secrets in Pod (env vars)
env:
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: username

##Use Secret as a volume
volumeMounts:
  - name: secret-vol
    mountPath: /etc/secret

volumes:
  - name: secret-vol
    secret:
      secretName: db-secret
